In [26]:
import os

import pandas as pd

from dotenv import load_dotenv

from sqlalchemy import create_engine

In [27]:
load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

In [28]:
engine = create_engine(DATABASE_URL)

print("✅ Connected to PostgreSQL Successfully")

✅ Connected to PostgreSQL Successfully

In [29]:
channels_df = pd.read_sql(
    "SELECT * FROM channels",
    engine
)

videos_df = pd.read_sql(
    "SELECT * FROM videos",
    engine
)

comments_df = pd.read_sql(
    "SELECT * FROM comments",
    engine
)

In [30]:
print("Channels :", channels_df.shape)

print("Videos   :", videos_df.shape)

print("Comments :", comments_df.shape)

Channels : (1, 8)
Videos   : (50, 13)
Comments : (4200, 21)

In [31]:
channels_df.head()

,channel_id,channel_name,description,country,published_at,subscriber_count,total_views,video_count
0,UCBwmMxybNva6P_5VmxjzwqA,Apna College,Started with a vision to provide learning that...,None,2020-08-05T16:09:28.304314Z,7700000,1284141607,1028

In [32]:
videos_df.head()

,video_id,channel_id,title,description,published_at,thumbnail,view_count,like_count,comment_count,duration,category_id,default_language,tags
0,c-HkAo8Bho4,UCBwmMxybNva6P_5VmxjzwqA,When is the Best Time to start Coding for Plac...,Start your Tech Placement Preparation early. B...,2026-06-29T13:15:51Z,https://i.ytimg.com/vi/c-HkAo8Bho4/hqdefault.jpg,69749,4520,104,PT1M20S,27,en,None
1,tkZmtsNPdHc,UCBwmMxybNva6P_5VmxjzwqA,FLIPKART OFF-Campus Interview Experience | Com...,Save time & study only what's needed for Place...,2026-06-18T16:24:41Z,https://i.ytimg.com/vi/tkZmtsNPdHc/hqdefault.jpg,66715,1919,227,PT34M59S,27,en,"C++,C++ coding,C++ full course,C++ placement c..."
2,922AALNzGBg,UCBwmMxybNva6P_5VmxjzwqA,Complete Interview Experiences for OFF-Campus ...,,2026-06-13T13:59:00Z,https://i.ytimg.com/vi/922AALNzGBg/hqdefault.jpg,77659,2591,61,PT31S,27,en,None
3,jNJH6uD5LQE,UCBwmMxybNva6P_5VmxjzwqA,Generative AI vs Agentic AI vs AI Agents,🚀 Get Placement Ready & learn from the best 👇\...,2026-06-12T16:27:09Z,https://i.ytimg.com/vi/jNJH6uD5LQE/hqdefault.jpg,274228,10329,414,PT11M14S,27,en,"C++,C++ coding,C++ full course,C++ placement c..."
4,5tUHOu6m0kw,UCBwmMxybNva6P_5VmxjzwqA,OFF Campus : Flipkart selection process for So...,,2026-06-10T14:57:37Z,https://i.ytimg.com/vi/5tUHOu6m0kw/hqdefault.jpg,174505,5836,61,PT2M58S,27,en,None

In [33]:
comments_df.head()

,comment_id,video_id,author,comment,likes,published_at,is_cleaned,sentiment,is_spam,contains_abusive_language,...,is_spam_checked,is_sentiment_checked,is_abusive_checked,word_count,character_count,comment_length,contains_link,contains_question,contains_exclamation,is_feature_engineered
0,Ugws4i6EzTKpFxqnwqx4AaABAg,w9319SXPOmg,@MalaKumari-4436,Didi ye bataeye ki mujhe English me koe bhi su...,0,2026-02-21T06:50:29Z,True,Neutral,False,False,...,True,True,True,18,98,Medium,False,False,False,True
1,Ugwtpj36gDxyrVsoh_t4AaABAg,oGdt3tzo074,@RajeevMishra498,Pls make an video on software Testing,0,2026-06-10T07:11:53Z,True,Positive,False,False,...,True,True,True,7,37,Medium,False,False,False,True
2,UgwvhcaqBZYWrCRlgRB4AaABAg,Tc_MJZ8XYYc,@parthvibhagat8272,"Hi ma'am, are you providing Data science roles...",0,2026-06-05T12:32:10Z,True,Positive,False,False,...,True,True,True,22,111,Long,False,True,False,True
3,Ugww-l1mXA_nwkbUkb14AaABAg,sMUWg_OlbbY,@himeshkar-g2f,6:02 i am also helping and is a part of making...,0,2025-11-11T16:39:20Z,True,Positive,False,False,...,True,True,True,31,138,Long,False,True,False,True
4,Ugww_5huF7wSfdKgrwx4AaABAg,Ebe9NFgQnnU,@Sonali33669,Can we start DSA with python instead of C++/j...,0,2026-06-28T04:53:04Z,True,Neutral,False,False,...,True,True,True,9,51,Medium,False,True,False,True

In [34]:
print("CHANNELS")

print(channels_df.columns.tolist())

print("\nVIDEOS")

print(videos_df.columns.tolist())

print("\nCOMMENTS")

print(comments_df.columns.tolist())

CHANNELS
['channel_id', 'channel_name', 'description', 'country', 'published_at', 'subscriber_count', 'total_views', 'video_count']

VIDEOS
['video_id', 'channel_id', 'title', 'description', 'published_at', 'thumbnail', 'view_count', 'like_count', 'comment_count', 'duration', 'category_id', 'default_language', 'tags']

COMMENTS
['comment_id', 'video_id', 'author', 'comment', 'likes', 'published_at', 'is_cleaned', 'sentiment', 'is_spam', 'contains_abusive_language', 'clean_comment', 'is_spam_checked', 'is_sentiment_checked', 'is_abusive_checked', 'word_count', 'character_count', 'comment_length', 'contains_link', 'contains_question', 'contains_exclamation', 'is_feature_engineered']

In [35]:
print("CHANNELS")

channels_df.info()

print("\nVIDEOS")

videos_df.info()

print("\nCOMMENTS")

comments_df.info()

CHANNELS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   channel_id        1 non-null      object
 1   channel_name      1 non-null      object
 2   description       1 non-null      object
 3   country           0 non-null      object
 4   published_at      1 non-null      object
 5   subscriber_count  1 non-null      int64
 6   total_views       1 non-null      int64
 7   video_count       1 non-null      int64
dtypes: int64(3), object(5)
memory usage: 196.0+ bytes

VIDEOS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   video_id          50 non-null     object
 1   channel_id        50 non-null     object
 2   title             50 non-null     object
 3   description       50 non-null     object
 4   published_at      50 non-null     object
 5   thumbnail         50 non-null     object
 6   view_count        50 non-null     int64
 7   like_count        50 non-null     int64
 8   comment_count     50 non-null     int64
 9   duration          50 non-null     object
 10  category_id       50 non-null     object
 11  default_language  50 non-null     object
 12  tags              34 non-null     object
dtypes: int64(3), object(10)
memory usage: 5.2+ KB

COMMENTS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   comment_id                 4200 non-null   object
 1   video_id                   4200 non-null   object
 2   author                     4200 non-null   object
 3   comment                    4200 non-null   object
 4   likes                      4200 non-null   int64
 5   published_at               4200 non-null   object
 6   is_cleaned                 4200 non-null   bool
 7   sentiment                  4200 non-null   object
 8   is_spam                    4200 non-null   bool
 9   contains_abusive_language  4200 non-null   bool
 10  clean_comment              4200 non-null   object
 11  is_spam_checked            4200 non-null   bool
 12  is_sentiment_checked       4200 non-null   bool
 13  is_abusive_checked         4200 non-null   bool
 14  word_count                 4200 non-null   int64
 15  character_count            4200 non-null   int64
 16  comment_length             4200 non-null   object
 17  contains_link              4200 non-null   bool
 18  contains_question          4200 non-null   bool
 19  contains_exclamation       4200 non-null   bool
 20  is_feature_engineered      4200 non-null   bool
dtypes: bool(10), int64(3), object(8)
memory usage: 402.1+ KB

In [36]:
print("CHANNELS")

print(channels_df.isnull().sum())

print()

print("VIDEOS")

print(videos_df.isnull().sum())

print()

print("COMMENTS")

print(comments_df.isnull().sum())

CHANNELS
channel_id          0
channel_name        0
description         0
country             1
published_at        0
subscriber_count    0
total_views         0
video_count         0
dtype: int64

VIDEOS
video_id             0
channel_id           0
title                0
description          0
published_at         0
thumbnail            0
view_count           0
like_count           0
comment_count        0
duration             0
category_id          0
default_language     0
tags                16
dtype: int64

COMMENTS
comment_id                   0
video_id                     0
author                       0
comment                      0
likes                        0
published_at                 0
is_cleaned                   0
sentiment                    0
is_spam                      0
contains_abusive_language    0
clean_comment                0
is_spam_checked              0
is_sentiment_checked         0
is_abusive_checked           0
word_count                   0
character_count              0
comment_length               0
contains_link                0
contains_question            0
contains_exclamation         0
is_feature_engineered        0
dtype: int64

In [37]:
print("Duplicate Channels :")

print(channels_df.duplicated().sum())

print()

print("Duplicate Videos :")

print(videos_df.duplicated().sum())

print()

print("Duplicate Comments :")

print(comments_df.duplicated().sum())

Duplicate Channels :
0

Duplicate Videos :
0

Duplicate Comments :
0

In [38]:
channels_df.describe(include="all")

,channel_id,channel_name,description,country,published_at,subscriber_count,total_views,video_count
count,1,1,1,0,1,1.0,1.000000e+00,1.0
unique,1,1,1,0,1,NaN,NaN,NaN
top,UCBwmMxybNva6P_5VmxjzwqA,Apna College,Started with a vision to provide learning that...,NaN,2020-08-05T16:09:28.304314Z,NaN,NaN,NaN
freq,1,1,1,NaN,1,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,7700000.0,1.284142e+09,1028.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,7700000.0,1.284142e+09,1028.0
25%,NaN,NaN,NaN,NaN,NaN,7700000.0,1.284142e+09,1028.0
50%,NaN,NaN,NaN,NaN,NaN,7700000.0,1.284142e+09,1028.0
75%,NaN,NaN,NaN,NaN,NaN,7700000.0,1.284142e+09,1028.0
max,NaN,NaN,NaN,NaN,NaN,7700000.0,1.284142e+09,1028.0

In [39]:
videos_df.describe(include="all")

,video_id,channel_id,title,description,published_at,thumbnail,view_count,like_count,comment_count,duration,category_id,default_language,tags
count,50,50,50,50,50,50,5.000000e+01,50.000000,50.000000,50,50,50,34
unique,50,1,50,28,50,50,NaN,NaN,NaN,46,1,1,1
top,c-HkAo8Bho4,UCBwmMxybNva6P_5VmxjzwqA,When is the Best Time to start Coding for Plac...,,2026-06-29T13:15:51Z,https://i.ytimg.com/vi/c-HkAo8Bho4/hqdefault.jpg,NaN,NaN,NaN,PT21M55S,27,en,"C++,C++ coding,C++ full course,C++ placement c..."
freq,1,50,1,14,1,1,NaN,NaN,NaN,2,50,50,34
mean,NaN,NaN,NaN,NaN,NaN,NaN,2.726732e+05,9396.060000,425.640000,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,2.124037e+05,8186.797755,433.242203,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,6.471500e+04,1919.000000,43.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.209710e+05,3727.750000,82.250000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2.135800e+05,6648.500000,240.500000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,3.480602e+05,11129.000000,661.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,1.058604e+06,38775.000000,1833.000000,NaN,NaN,NaN,NaN

In [40]:
comments_df.describe(include="all")

,comment_id,video_id,author,comment,likes,published_at,is_cleaned,sentiment,is_spam,contains_abusive_language,...,is_spam_checked,is_sentiment_checked,is_abusive_checked,word_count,character_count,comment_length,contains_link,contains_question,contains_exclamation,is_feature_engineered
count,4200,4200,4200,4200,4200.000000,4200,4200,4200,4200,4200,...,4200,4200,4200,4200.000000,4200.000000,4200,4200,4200,4200,4200
unique,4200,50,3598,3840,NaN,4191,1,3,2,2,...,1,1,1,NaN,NaN,3,2,2,2,1
top,Ugws4i6EzTKpFxqnwqx4AaABAg,w9319SXPOmg,@ravangaming6008,❤️,NaN,2026-03-22T16:33:19Z,True,Neutral,False,False,...,True,True,True,NaN,NaN,Medium,False,False,False,True
freq,1,100,25,46,NaN,3,4200,2013,4169,3912,...,4200,4200,4200,NaN,NaN,2394,4158,3468,4076,4200
mean,NaN,NaN,NaN,NaN,2.826905,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14.874524,80.000238,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,18.541298,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20.593174,131.030271,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.000000,27.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.000000,49.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.000000,93.000000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,381.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,502.000000,3173.000000,NaN,NaN,NaN,NaN,NaN

In [41]:
print(channels_df.dtypes)

channel_id          object
channel_name        object
description         object
country             object
published_at        object
subscriber_count     int64
total_views          int64
video_count          int64
dtype: object

In [42]:
print(comments_df.dtypes)

comment_id                   object
video_id                     object
author                       object
comment                      object
likes                         int64
published_at                 object
is_cleaned                     bool
sentiment                    object
is_spam                        bool
contains_abusive_language      bool
clean_comment                object
is_spam_checked                bool
is_sentiment_checked           bool
is_abusive_checked             bool
word_count                    int64
character_count               int64
comment_length               object
contains_link                  bool
contains_question              bool
contains_exclamation           bool
is_feature_engineered          bool
dtype: object

In [43]:
# # 📌 Notebook Summary

# Successfully connected to the PostgreSQL database and loaded all project tables into Pandas DataFrames.

# ### Loaded Tables

# - Channels
# - Videos
# - Comments

# ### Initial Analysis Performed

# - Dataset Shape
# - Head Records
# - Column Inspection
# - Data Types
# - Missing Values
# - Duplicate Records
# - Statistical Summary

# This notebook confirms that the ETL pipeline has successfully populated the database and the data is ready for Exploratory Data Analysis (EDA).