In [1]:
import os

import pandas as pd
import numpy as np

from dotenv import load_dotenv

from sqlalchemy import create_engine

import plotly.express as px
import plotly.graph_objects as go

In [2]:
load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)

In [3]:
channels_df = pd.read_sql(
    "SELECT * FROM channels",
    engine
)

videos_df = pd.read_sql(
    "SELECT * FROM videos",
    engine
)

comments_df = pd.read_sql(
    "SELECT * FROM comments",
    engine
)

In [4]:
print("Channels :", channels_df.shape)

print("Videos :", videos_df.shape)

print("Comments :", comments_df.shape)

Channels : (1, 8)
Videos : (50, 13)
Comments : (4200, 21)

In [5]:
total_subscribers = channels_df["subscriber_count"].sum()

total_views = channels_df["total_views"].sum()

total_videos = len(videos_df)

total_comments = len(comments_df)

positive_comments = (
    comments_df["sentiment"] == "Positive"
).sum()

neutral_comments = (
    comments_df["sentiment"] == "Neutral"
).sum()

negative_comments = (
    comments_df["sentiment"] == "Negative"
).sum()

spam_comments = (
    comments_df["is_spam"] == True
).sum()

abusive_comments = (
    comments_df["contains_abusive_language"] == True
).sum()

In [6]:
kpi_df = pd.DataFrame({

    "Metric":[

        "Subscribers",
        "Views",
        "Videos",
        "Comments",
        "Positive",
        "Neutral",
        "Negative",
        "Spam",
        "Abusive"

    ],

    "Value":[

        total_subscribers,
        total_views,
        total_videos,
        total_comments,
        positive_comments,
        neutral_comments,
        negative_comments,
        spam_comments,
        abusive_comments

    ]

})

kpi_df

        Metric       Value
0  Subscribers     7700000
1        Views  1284141607
2       Videos          50
3     Comments        4200
4     Positive        1976
5      Neutral        2013
6     Negative         211
7         Spam          31
8      Abusive         288

In [7]:
fig = px.bar(

    kpi_df,

    x="Metric",

    y="Value",

    title="InfluenceIQ KPI Dashboard",

    text="Value"

)

fig.show()

In [9]:
fig = go.Figure()

fig.add_trace(

    go.Indicator(

        mode="number",

        value=total_views,

        title={"text":"Total Views"}

    )

)

fig.show()

In [10]:
fig = go.Figure()

fig.add_trace(

    go.Indicator(

        mode="number",

        value=total_subscribers,

        title={"text":"Subscribers"}

    )

)

fig.show()

In [11]:
fig = go.Figure()

fig.add_trace(

    go.Indicator(

        mode="number",

        value=total_videos,

        title={"text":"Videos"}

    )

)

fig.show()

In [12]:
fig = go.Figure()

fig.add_trace(

    go.Indicator(

        mode="number",

        value=total_comments,

        title={"text":"Comments"}

    )

)

fig.show()

In [13]:
average_views = videos_df["view_count"].mean()

average_views

np.float64(272673.24)

In [14]:
average_likes = videos_df["like_count"].mean()

average_likes

np.float64(9396.06)

In [15]:
average_comments = videos_df["comment_count"].mean()

average_comments

np.float64(425.64)

In [16]:
summary = pd.DataFrame({

    "Metric":[

        "Average Views",

        "Average Likes",

        "Average Comments"

    ],

    "Value":[

        average_views,

        average_likes,

        average_comments

    ]

})

summary

             Metric      Value
0     Average Views  272673.24
1     Average Likes    9396.06
2  Average Comments     425.64

In [17]:
fig = px.bar(

    summary,

    x="Metric",

    y="Value",

    text="Value",

    title="Average Engagement Metrics"

)

fig.show()

In [18]:
top_views = videos_df.nlargest(
    10,
    "view_count"
)

fig = px.bar(

    top_views,

    x="view_count",

    y="title",

    orientation="h",

    title="Top 10 Most Viewed Videos",

    text="view_count"

)

fig.update_layout(

    yaxis=dict(autorange="reversed")

)

fig.show()

In [19]:
top_likes = videos_df.nlargest(
    10,
    "like_count"
)

fig = px.bar(

    top_likes,

    x="like_count",

    y="title",

    orientation="h",

    title="Top 10 Most Liked Videos",

    text="like_count"

)

fig.update_layout(

    yaxis=dict(autorange="reversed")

)

fig.show()

In [20]:
top_comments = videos_df.nlargest(
    10,
    "comment_count"
)

fig = px.bar(

    top_comments,

    x="comment_count",

    y="title",

    orientation="h",

    title="Top 10 Most Commented Videos",

    text="comment_count"

)

fig.update_layout(

    yaxis=dict(autorange="reversed")

)

fig.show()

In [21]:
videos_df["engagement_rate"] = (

    videos_df["like_count"]

    +

    videos_df["comment_count"]

) / videos_df["view_count"] * 100

In [22]:
videos_df[
    [

        "title",

        "engagement_rate"

    ]

].head()

                                               title  engagement_rate
0  When is the Best Time to start Coding for Plac...         6.629486
1  FLIPKART OFF-Campus Interview Experience | Com...         3.216668
2  Complete Interview Experiences for OFF-Campus ...         3.414929
3           Generative AI vs Agentic AI vs AI Agents         3.917543
4  OFF Campus : Flipkart selection process for So...         3.379273

In [23]:
top_engagement = videos_df.nlargest(

    10,

    "engagement_rate"

)

fig = px.bar(

    top_engagement,

    x="engagement_rate",

    y="title",

    orientation="h",

    text="engagement_rate",

    title="Top 10 Engagement Rate"

)

fig.update_layout(

    yaxis=dict(autorange="reversed")

)

fig.show()

In [24]:
fig = px.scatter(

    videos_df,

    x="view_count",

    y="like_count",

    hover_name="title",

    title="Views vs Likes"

)

fig.show()

In [25]:
fig = px.scatter(

    videos_df,

    x="view_count",

    y="comment_count",

    hover_name="title",

    title="Views vs Comments"

)

fig.show()

In [26]:
fig = px.scatter(

    videos_df,

    x="like_count",

    y="comment_count",

    hover_name="title",

    title="Likes vs Comments"

)

fig.show()

In [27]:
fig = px.scatter(

    videos_df,

    x="view_count",

    y="like_count",

    size="comment_count",

    hover_name="title",

    title="Bubble Chart : Views, Likes & Comments"

)

fig.show()

In [28]:
fig = px.histogram(

    videos_df,

    x="duration",

    title="Video Duration Distribution"

)

fig.show()

In [29]:
fig = px.histogram(

    videos_df,

    x="view_count",

    nbins=20,

    title="View Count Distribution"

)

fig.show()

In [30]:
fig = px.histogram(

    videos_df,

    x="like_count",

    nbins=20,

    title="Like Distribution"

)

fig.show()

In [31]:
fig = px.histogram(

    videos_df,

    x="comment_count",

    nbins=20,

    title="Comment Distribution"

)

fig.show()

In [32]:
top_engagement[
    [

        "title",

        "engagement_rate",

        "view_count",

        "like_count",

        "comment_count"

    ]

]

,title,engagement_rate,view_count,like_count,comment_count
0,When is the Best Time to start Coding for Plac...,6.629486,69749,4520,104
15,"WAKE UP CALL for 1st, 2nd year students - Know...",5.486483,269444,13940,843
10,5 Things you should know before Engineering | ...,5.246948,208445,10398,539
27,17 LPA+ @ HPE : Best Strategy for Placement🚀,4.462910,433596,19216,135
14,How to get Placement in 6 months ? Study Plan ...,4.387601,195665,8127,458
18,The Complete Data Science RoadMap | from Basic...,4.321307,469395,19351,933
38,Top Skills that every Software Engineer MUST l...,4.251208,291917,11726,684
36,How to Start Coding ? Learn Programming for Be...,4.203831,965976,38775,1833
24,Data Analyst vs Data Scientist vs AI Engineer ...,4.145722,281495,11078,592
25,The most important TIME in College. Importance...,4.137669,397156,16204,229

In [33]:
print("========== VIDEO PERFORMANCE ==========\n")

print(

f"Average Views : {videos_df['view_count'].mean():,.0f}"

)

print(

f"Average Likes : {videos_df['like_count'].mean():,.0f}"

)

print(

f"Average Comments : {videos_df['comment_count'].mean():,.0f}"

)

print(

f"Highest Engagement : {videos_df['engagement_rate'].max():.2f}%"

)

========== VIDEO PERFORMANCE ==========

Average Views : 272,673
Average Likes : 9,396
Average Comments : 426
Highest Engagement : 6.63%

In [ ]:
# # 📊 Part 2 Summary

# The following analyses were completed:

# - Top Viewed Videos
# - Top Liked Videos
# - Top Commented Videos
# - Engagement Rate
# - Views vs Likes
# - Views vs Comments
# - Likes vs Comments
# - Bubble Chart
# - Video Distribution

# These visualizations help identify the best-performing content and understand audience engagement patterns.